### ISSUE TITLE
BioNanoAnalyst - KeyError

### ISSUE THREAD

**Issue by AlanTracey99** [AppliedBioinformatics/BioNanoAnalyst#2]
I get the following error a couple of minutes after setting BioNanoAnalyst running.  It seems to be due to be something to do with contig IDs.

Process Process-31:
Traceback (most recent call last):
  File "/software/pathogen/external/apps/usr/local/Python-2.7.13/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/software/pathogen/external/apps/usr/local/Python-2.7.13/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/software/pathogen/external/apps/usr/local/BioNanoAnalyst-20170928/scripts/Analysis.py", line 345, in alignedInf
    name = self.ref_id[RefCtgId]
KeyError: 67

Here are my 13 scaffold fasta headers:
>Super-Scaffold_1
>Super-Scaffold_2
>Super-Scaffold_3
>Super-Scaffold_4
>Super-Scaffold_5
>Super-Scaffold_7
>Super-Scaffold_10
>Super-Scaffold_11
>Super-Scaffold_12
>Super-Scaffold_67
>Super-Scaffold_70
>Super-Scaffold_72
>Super-Scaffold_133

And the first 3 columns of my xmap file:

#f int        	int  
1	1	1
2	2	2
3	3	3
4	4	4
5	69	4
6	5	5
7	9	7
8	7	7
9	8	7
10	10	10
11	11	11
12	136	12
13	12	12
14	67	67
15	70	70
16	202	70
17	72	72
18	133	133

**Comment by yyx8671** [comment]
Hi @AlanTracey99, 

It seems your 'RefContigID' in your xmap file is the super_scaffold ID. To my understanding, the 'RefContigID' is calculated from 1 to the last header, for instance Super-Scaffold_1 should be RefContigID 1 and Super-Scaffold_133 should be RefContigID 13. In your case, they don't math with each  other and error raised.

**Comment by AlanTracey99** [comment]
Hi Andy

That's right.  What I don't understand is why they don't match up.

Do you have some data that we could take a look at please?

Is there something we need to do to our sequence fasta headers before
running BioNanoAnalyst to make the naming acceptable?

Thanks,
Alan

**Comment by yyx8671** [comment]
Hi Alan, 
I'm not sure how did you get your xmap file. If you don't mind, you may try our another script: https://github.com/appliedbioinformatics/runBNG to regenerate your xmap file and try BioNanoAnalyst again. 

We have also provided a test file and you can have a test.

Cheers,
Andy

**Comment by AlanTracey99** [comment]
Hi Andy

Thanks for this.  I've attempted to run runBNG, but it hasn't produced an
xmap file.  The only files I have are:

-rw-r--r-- 1 alt hsg   4255 Sep 20 18:34 Hmic.stdout
-rw-r--r-- 1 alt hsg 130695 Sep 20 18:34 Hmic.rmap
-rw-r--r-- 1 alt hsg   1125 Sep 20 18:34 Hmic_repeatStats.txt

I'm not sure where to go next with this....

Thanks,
Alan
