### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)

### ISSUE THREAD

**Issue by mzahm** [AppliedBioinformatics/BioNanoAnalyst#5]
Hi,

When I try to run `python2.7 App.py` I have an error message:
```
Traceback (most recent call last):
  File "App.py", line 35, in <module>
    from Analysis import*
  File "/home/mzahm/Téléchargements/Softwares/BioNanoAnalyst-master/scripts/Analysis.py", line 20, in <module>
    import matplotlib.pyplot as plt
  File "/home/mzahm/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 72, in <module>
    from matplotlib.backends import pylab_setup
  File "/home/mzahm/anaconda2/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()
  File "/home/mzahm/anaconda2/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 16, in <genexpr>
    if not line.startswith('  File "<frozen importlib._bootstrap'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
```
I am working on Fedora. Do you have any idea to fix it?

Thanks, Margot

**Comment by yyx8671** [comment]
Hi,
It seems your encoding!=utf8. You may set it using "sys.setdefaultencoding('utf8')".
Cheers,
Andy

**Comment by mzahm** [comment]
Thanks it works!
