### ISSUE TITLE
Test data - IOError: [Errno 4] Interrupted system call

### ISSUE THREAD

**Issue by marcelauliano** [AppliedBioinformatics/BioNanoAnalyst#7]
Hey guys, 
I've setup a conda system to use BionanoAnalyst: the env was setup with python 2.7.3 and I had problems to install PySide, which I ended up doing with 'conda install --name py273 -c terradue pyqt4'

But then, I had a compatibility problem as I tried to start the program python App.py and got:
ImportError: /home/muliano/anaconda3/envs/py273/lib/python2.7/site-packages/PySide/../../../libshiboken-python2.7.so.1.2: undefined symbol: _PyTrash_thread_destroy_chain

So, I installed another version of pyqt: conda install --name py273 -c anaconda pyqt=4.11.4 

and then it worked. But once I tried to run the example data I got:

Traceback (most recent call last):
  File "App.py", line 701, in analyse
    self.running.getDetail()
  File "/home/muliano/script/BioNanoAnalyst/scripts/Analysis.py", line 215, in getDetail
    pairwise = np.concatenate((pairwise, q.get()),axis=0)
  File "/home/muliano/anaconda3/envs/py273/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
IOError: [Errno 4] Interrupted system call

So really don't know how to proceed from here. Is it a pyqt and python2.7.3 compatibility problem?

Another question is: would it be enough to open a 3.5Gb mammal assembly with a local computer with 30GbRAM and 4 CPUs?

Thanks guys!

**Comment by yyx8671** [comment]
Hi @marcelauliano, 

I know it is annoying to install Qt4. I haven't tested this in using Conda. I used Canopy and it works. Not sure which system you use. Recently, @mp15 has made a change to use Qt5 instead of Qt4 (https://github.com/mp15/BioNanoAnalyst/tree/qt5_conversion). I haven't had a chance to test it. If you'd like to try, you may go for it. 

It is possible to check your mammal assembly with your local computer. However, it may run for several hours. You may want to get the xmap and cmap files first and then run BioNanoAnalyst.

Let me know if you have any questions.

Cheers,
Andy

**Comment by mp15** [comment]
I managed to get the Qt5 version running but I'm afraid I haven't got around to fixing the paths returned from the File dialogs nor testing. If someone else has the time and motivation they could build on it though?

> On 13 Oct 2018, at 03:15, Andy Yuan <notifications@github.com> wrote:
> 
> Hi @marcelauliano,
> 
> I know it is annoying to install Qt4. I haven't tested this in using Conda. I used Canopy and it works. Not sure which system you use. Recently, @mp15 has made a change to use Qt5 instead of Qt4 (https://github.com/mp15/BioNanoAnalyst/tree/qt5_conversion). I haven't had a chance to test it. If you'd like to try, you may go for it.
> 
> It is possible to check your mammal assembly with your local computer. However, it may run for several hours. You may want to get the xmap and cmap files first and then run BioNanoAnalyst.
> 
> Let me know if you have any questions.
> 
> Cheers,
> Andy
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
